openapi: 3.0.0
info:
  title: vvot05-boot-gateway
  version: 1.0.0
paths:
  /:
    get:
      parameters:
        - name: face
          in: query
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: object_storage
        bucket: itis-2022-2023-vvot05-faces
        object: '{face}'
        error_object: error.html
        presigned_redirect: true
        service_account_id:
  photo:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: itis-2022-2023-vvot05-photos
        object: '{id}'
        error_object: error.html
        presigned_redirect: true
        service_account_id:
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: string
